FROM golang:1.24-alpine AS builder

WORKDIR /app
COPY . .

# Build server
RUN go build -o icebox-server cmd/icebox-server/main.go

FROM alpine:latest
RUN apk --no-cache add ca-certificates

WORKDIR /root/
COPY --from=builder /app/icebox-server .
COPY --from=builder /app/icebox-server.yml .

EXPOSE 8080 5432

CMD ["./icebox-server"]
