FROM golang:1.24-alpine AS builder

WORKDIR /app
COPY . .

# Build client
RUN go build -o ranger-client cmd/ranger-client/main.go

FROM alpine:latest
RUN apk --no-cache add ca-certificates

WORKDIR /root/
COPY --from=builder /app/ranger-client .
COPY --from=builder /app/ranger-client.yml .

CMD ["./ranger-client", "--help"]
